//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PimIntegration.Tasks.PIMServiceEndpoint {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductQueryRequestItem", Namespace="http://schemas.datacontract.org/2004/07/web4Sound.Contracts.Products")]
    [System.SerializableAttribute()]
    public partial class ProductQueryRequestItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SKUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VendorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCodeVendorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductGroupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductSubgroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BrandIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SeriesIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MasterModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarketNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsNewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowOrderingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DisplayWebField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedOnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SKU {
            get {
                return this.SKUField;
            }
            set {
                if ((object.ReferenceEquals(this.SKUField, value) != true)) {
                    this.SKUField = value;
                    this.RaisePropertyChanged("SKU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VendorId {
            get {
                return this.VendorIdField;
            }
            set {
                if ((this.VendorIdField.Equals(value) != true)) {
                    this.VendorIdField = value;
                    this.RaisePropertyChanged("VendorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string ProductCodeVendor {
            get {
                return this.ProductCodeVendorField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCodeVendorField, value) != true)) {
                    this.ProductCodeVendorField = value;
                    this.RaisePropertyChanged("ProductCodeVendor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string EAN {
            get {
                return this.EANField;
            }
            set {
                if ((object.ReferenceEquals(this.EANField, value) != true)) {
                    this.EANField = value;
                    this.RaisePropertyChanged("EAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int ProductGroupId {
            get {
                return this.ProductGroupIdField;
            }
            set {
                if ((this.ProductGroupIdField.Equals(value) != true)) {
                    this.ProductGroupIdField = value;
                    this.RaisePropertyChanged("ProductGroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string ProductSubgroupName {
            get {
                return this.ProductSubgroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductSubgroupNameField, value) != true)) {
                    this.ProductSubgroupNameField = value;
                    this.RaisePropertyChanged("ProductSubgroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int BrandId {
            get {
                return this.BrandIdField;
            }
            set {
                if ((this.BrandIdField.Equals(value) != true)) {
                    this.BrandIdField = value;
                    this.RaisePropertyChanged("BrandId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int SeriesId {
            get {
                return this.SeriesIdField;
            }
            set {
                if ((this.SeriesIdField.Equals(value) != true)) {
                    this.SeriesIdField = value;
                    this.RaisePropertyChanged("SeriesId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string MasterModel {
            get {
                return this.MasterModelField;
            }
            set {
                if ((object.ReferenceEquals(this.MasterModelField, value) != true)) {
                    this.MasterModelField = value;
                    this.RaisePropertyChanged("MasterModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string MarketName {
            get {
                return this.MarketNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MarketNameField, value) != true)) {
                    this.MarketNameField = value;
                    this.RaisePropertyChanged("MarketName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public bool IsNew {
            get {
                return this.IsNewField;
            }
            set {
                if ((this.IsNewField.Equals(value) != true)) {
                    this.IsNewField = value;
                    this.RaisePropertyChanged("IsNew");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public bool AllowOrdering {
            get {
                return this.AllowOrderingField;
            }
            set {
                if ((this.AllowOrderingField.Equals(value) != true)) {
                    this.AllowOrderingField = value;
                    this.RaisePropertyChanged("AllowOrdering");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public bool DisplayWeb {
            get {
                return this.DisplayWebField;
            }
            set {
                if ((this.DisplayWebField.Equals(value) != true)) {
                    this.DisplayWebField = value;
                    this.RaisePropertyChanged("DisplayWeb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public System.DateTime CreatedOn {
            get {
                return this.CreatedOnField;
            }
            set {
                if ((this.CreatedOnField.Equals(value) != true)) {
                    this.CreatedOnField = value;
                    this.RaisePropertyChanged("CreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public System.DateTime UpdatedOn {
            get {
                return this.UpdatedOnField;
            }
            set {
                if ((this.UpdatedOnField.Equals(value) != true)) {
                    this.UpdatedOnField = value;
                    this.RaisePropertyChanged("UpdatedOn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductQueryResponseItem", Namespace="http://schemas.datacontract.org/2004/07/web4Sound.Contracts.Products")]
    [System.SerializableAttribute()]
    public partial class ProductQueryResponseItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SKUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContainerSKUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductGroupCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductGroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductSubgroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContainerModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VariantModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PimIntegration.Tasks.PIMServiceEndpoint.ProductQueryResponseMarketItem[] MarketsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedOnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SKU {
            get {
                return this.SKUField;
            }
            set {
                if ((object.ReferenceEquals(this.SKUField, value) != true)) {
                    this.SKUField = value;
                    this.RaisePropertyChanged("SKU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string ContainerSKU {
            get {
                return this.ContainerSKUField;
            }
            set {
                if ((object.ReferenceEquals(this.ContainerSKUField, value) != true)) {
                    this.ContainerSKUField = value;
                    this.RaisePropertyChanged("ContainerSKU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string ProductGroupCode {
            get {
                return this.ProductGroupCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductGroupCodeField, value) != true)) {
                    this.ProductGroupCodeField = value;
                    this.RaisePropertyChanged("ProductGroupCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string ProductGroupName {
            get {
                return this.ProductGroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductGroupNameField, value) != true)) {
                    this.ProductGroupNameField = value;
                    this.RaisePropertyChanged("ProductGroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string ProductSubgroupName {
            get {
                return this.ProductSubgroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductSubgroupNameField, value) != true)) {
                    this.ProductSubgroupNameField = value;
                    this.RaisePropertyChanged("ProductSubgroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string BrandCode {
            get {
                return this.BrandCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandCodeField, value) != true)) {
                    this.BrandCodeField = value;
                    this.RaisePropertyChanged("BrandCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string BrandName {
            get {
                return this.BrandNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandNameField, value) != true)) {
                    this.BrandNameField = value;
                    this.RaisePropertyChanged("BrandName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Series {
            get {
                return this.SeriesField;
            }
            set {
                if ((object.ReferenceEquals(this.SeriesField, value) != true)) {
                    this.SeriesField = value;
                    this.RaisePropertyChanged("Series");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string ContainerModel {
            get {
                return this.ContainerModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ContainerModelField, value) != true)) {
                    this.ContainerModelField = value;
                    this.RaisePropertyChanged("ContainerModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string VariantModel {
            get {
                return this.VariantModelField;
            }
            set {
                if ((object.ReferenceEquals(this.VariantModelField, value) != true)) {
                    this.VariantModelField = value;
                    this.RaisePropertyChanged("VariantModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string FullModel {
            get {
                return this.FullModelField;
            }
            set {
                if ((object.ReferenceEquals(this.FullModelField, value) != true)) {
                    this.FullModelField = value;
                    this.RaisePropertyChanged("FullModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string EAN {
            get {
                return this.EANField;
            }
            set {
                if ((object.ReferenceEquals(this.EANField, value) != true)) {
                    this.EANField = value;
                    this.RaisePropertyChanged("EAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public PimIntegration.Tasks.PIMServiceEndpoint.ProductQueryResponseMarketItem[] Markets {
            get {
                return this.MarketsField;
            }
            set {
                if ((object.ReferenceEquals(this.MarketsField, value) != true)) {
                    this.MarketsField = value;
                    this.RaisePropertyChanged("Markets");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public System.DateTime CreatedOn {
            get {
                return this.CreatedOnField;
            }
            set {
                if ((this.CreatedOnField.Equals(value) != true)) {
                    this.CreatedOnField = value;
                    this.RaisePropertyChanged("CreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public System.DateTime ModifiedOn {
            get {
                return this.ModifiedOnField;
            }
            set {
                if ((this.ModifiedOnField.Equals(value) != true)) {
                    this.ModifiedOnField = value;
                    this.RaisePropertyChanged("ModifiedOn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductQueryResponseMarketItem", Namespace="http://schemas.datacontract.org/2004/07/web4Sound.Contracts.Products")]
    [System.SerializableAttribute()]
    public partial class ProductQueryResponseMarketItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarketField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ERPGroupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ERPCategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsNewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowOrderingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DisplayWebField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VendorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCodeVendorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ERPIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedOnVendorImportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VendorStockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VendorStockLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal VendorPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal VendorRecPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DiscountPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal VATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StockLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShopStockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SpecialTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Market {
            get {
                return this.MarketField;
            }
            set {
                if ((object.ReferenceEquals(this.MarketField, value) != true)) {
                    this.MarketField = value;
                    this.RaisePropertyChanged("Market");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string ShortDescription {
            get {
                return this.ShortDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortDescriptionField, value) != true)) {
                    this.ShortDescriptionField = value;
                    this.RaisePropertyChanged("ShortDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string LongDescription {
            get {
                return this.LongDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.LongDescriptionField, value) != true)) {
                    this.LongDescriptionField = value;
                    this.RaisePropertyChanged("LongDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string CategoryNames {
            get {
                return this.CategoryNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNamesField, value) != true)) {
                    this.CategoryNamesField = value;
                    this.RaisePropertyChanged("CategoryNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int ERPGroupId {
            get {
                return this.ERPGroupIdField;
            }
            set {
                if ((this.ERPGroupIdField.Equals(value) != true)) {
                    this.ERPGroupIdField = value;
                    this.RaisePropertyChanged("ERPGroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int ERPCategoryId {
            get {
                return this.ERPCategoryIdField;
            }
            set {
                if ((this.ERPCategoryIdField.Equals(value) != true)) {
                    this.ERPCategoryIdField = value;
                    this.RaisePropertyChanged("ERPCategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public bool IsNew {
            get {
                return this.IsNewField;
            }
            set {
                if ((this.IsNewField.Equals(value) != true)) {
                    this.IsNewField = value;
                    this.RaisePropertyChanged("IsNew");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public bool AllowOrdering {
            get {
                return this.AllowOrderingField;
            }
            set {
                if ((this.AllowOrderingField.Equals(value) != true)) {
                    this.AllowOrderingField = value;
                    this.RaisePropertyChanged("AllowOrdering");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public bool DisplayWeb {
            get {
                return this.DisplayWebField;
            }
            set {
                if ((this.DisplayWebField.Equals(value) != true)) {
                    this.DisplayWebField = value;
                    this.RaisePropertyChanged("DisplayWeb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public int VendorId {
            get {
                return this.VendorIdField;
            }
            set {
                if ((this.VendorIdField.Equals(value) != true)) {
                    this.VendorIdField = value;
                    this.RaisePropertyChanged("VendorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string ProductCodeVendor {
            get {
                return this.ProductCodeVendorField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCodeVendorField, value) != true)) {
                    this.ProductCodeVendorField = value;
                    this.RaisePropertyChanged("ProductCodeVendor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public int ERPId {
            get {
                return this.ERPIdField;
            }
            set {
                if ((this.ERPIdField.Equals(value) != true)) {
                    this.ERPIdField = value;
                    this.RaisePropertyChanged("ERPId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public System.DateTime UpdatedOnVendorImport {
            get {
                return this.UpdatedOnVendorImportField;
            }
            set {
                if ((this.UpdatedOnVendorImportField.Equals(value) != true)) {
                    this.UpdatedOnVendorImportField = value;
                    this.RaisePropertyChanged("UpdatedOnVendorImport");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public int VendorStock {
            get {
                return this.VendorStockField;
            }
            set {
                if ((this.VendorStockField.Equals(value) != true)) {
                    this.VendorStockField = value;
                    this.RaisePropertyChanged("VendorStock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public string VendorStockLevel {
            get {
                return this.VendorStockLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.VendorStockLevelField, value) != true)) {
                    this.VendorStockLevelField = value;
                    this.RaisePropertyChanged("VendorStockLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public decimal VendorPrice {
            get {
                return this.VendorPriceField;
            }
            set {
                if ((this.VendorPriceField.Equals(value) != true)) {
                    this.VendorPriceField = value;
                    this.RaisePropertyChanged("VendorPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public decimal VendorRecPrice {
            get {
                return this.VendorRecPriceField;
            }
            set {
                if ((this.VendorRecPriceField.Equals(value) != true)) {
                    this.VendorRecPriceField = value;
                    this.RaisePropertyChanged("VendorRecPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public decimal DiscountPrice {
            get {
                return this.DiscountPriceField;
            }
            set {
                if ((this.DiscountPriceField.Equals(value) != true)) {
                    this.DiscountPriceField = value;
                    this.RaisePropertyChanged("DiscountPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public decimal VAT {
            get {
                return this.VATField;
            }
            set {
                if ((this.VATField.Equals(value) != true)) {
                    this.VATField = value;
                    this.RaisePropertyChanged("VAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=22)]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=23)]
        public int Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=24)]
        public string StockLevel {
            get {
                return this.StockLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.StockLevelField, value) != true)) {
                    this.StockLevelField = value;
                    this.RaisePropertyChanged("StockLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=25)]
        public string ShopStock {
            get {
                return this.ShopStockField;
            }
            set {
                if ((object.ReferenceEquals(this.ShopStockField, value) != true)) {
                    this.ShopStockField = value;
                    this.RaisePropertyChanged("ShopStock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=26)]
        public int SpecialType {
            get {
                return this.SpecialTypeField;
            }
            set {
                if ((this.SpecialTypeField.Equals(value) != true)) {
                    this.SpecialTypeField = value;
                    this.RaisePropertyChanged("SpecialType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductUpdateRequestItem", Namespace="http://schemas.datacontract.org/2004/07/web4Sound.Contracts.Products")]
    [System.SerializableAttribute()]
    public partial class ProductUpdateRequestItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SKUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarketNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VendorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCodeVendorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VendorStockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VendorStockLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal VendorPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RecommendedPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShopStockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal OldPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PriceChangeDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CampaignPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CampaignIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CampaignNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CampaignStartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CampaignEndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal VATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EAN4SoundField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SKU {
            get {
                return this.SKUField;
            }
            set {
                if ((object.ReferenceEquals(this.SKUField, value) != true)) {
                    this.SKUField = value;
                    this.RaisePropertyChanged("SKU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string MarketName {
            get {
                return this.MarketNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MarketNameField, value) != true)) {
                    this.MarketNameField = value;
                    this.RaisePropertyChanged("MarketName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int VendorId {
            get {
                return this.VendorIdField;
            }
            set {
                if ((this.VendorIdField.Equals(value) != true)) {
                    this.VendorIdField = value;
                    this.RaisePropertyChanged("VendorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string ProductCodeVendor {
            get {
                return this.ProductCodeVendorField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCodeVendorField, value) != true)) {
                    this.ProductCodeVendorField = value;
                    this.RaisePropertyChanged("ProductCodeVendor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int VendorStock {
            get {
                return this.VendorStockField;
            }
            set {
                if ((this.VendorStockField.Equals(value) != true)) {
                    this.VendorStockField = value;
                    this.RaisePropertyChanged("VendorStock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string VendorStockLevel {
            get {
                return this.VendorStockLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.VendorStockLevelField, value) != true)) {
                    this.VendorStockLevelField = value;
                    this.RaisePropertyChanged("VendorStockLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public decimal VendorPrice {
            get {
                return this.VendorPriceField;
            }
            set {
                if ((this.VendorPriceField.Equals(value) != true)) {
                    this.VendorPriceField = value;
                    this.RaisePropertyChanged("VendorPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public decimal RecommendedPrice {
            get {
                return this.RecommendedPriceField;
            }
            set {
                if ((this.RecommendedPriceField.Equals(value) != true)) {
                    this.RecommendedPriceField = value;
                    this.RaisePropertyChanged("RecommendedPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int Stock {
            get {
                return this.StockField;
            }
            set {
                if ((this.StockField.Equals(value) != true)) {
                    this.StockField = value;
                    this.RaisePropertyChanged("Stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string ShopStock {
            get {
                return this.ShopStockField;
            }
            set {
                if ((object.ReferenceEquals(this.ShopStockField, value) != true)) {
                    this.ShopStockField = value;
                    this.RaisePropertyChanged("ShopStock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public decimal OldPrice {
            get {
                return this.OldPriceField;
            }
            set {
                if ((this.OldPriceField.Equals(value) != true)) {
                    this.OldPriceField = value;
                    this.RaisePropertyChanged("OldPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public System.DateTime PriceChangeDate {
            get {
                return this.PriceChangeDateField;
            }
            set {
                if ((this.PriceChangeDateField.Equals(value) != true)) {
                    this.PriceChangeDateField = value;
                    this.RaisePropertyChanged("PriceChangeDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public decimal CampaignPrice {
            get {
                return this.CampaignPriceField;
            }
            set {
                if ((this.CampaignPriceField.Equals(value) != true)) {
                    this.CampaignPriceField = value;
                    this.RaisePropertyChanged("CampaignPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=14)]
        public int CampaignId {
            get {
                return this.CampaignIdField;
            }
            set {
                if ((this.CampaignIdField.Equals(value) != true)) {
                    this.CampaignIdField = value;
                    this.RaisePropertyChanged("CampaignId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public string CampaignName {
            get {
                return this.CampaignNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CampaignNameField, value) != true)) {
                    this.CampaignNameField = value;
                    this.RaisePropertyChanged("CampaignName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public System.DateTime CampaignStartDate {
            get {
                return this.CampaignStartDateField;
            }
            set {
                if ((this.CampaignStartDateField.Equals(value) != true)) {
                    this.CampaignStartDateField = value;
                    this.RaisePropertyChanged("CampaignStartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=17)]
        public System.DateTime CampaignEndDate {
            get {
                return this.CampaignEndDateField;
            }
            set {
                if ((this.CampaignEndDateField.Equals(value) != true)) {
                    this.CampaignEndDateField = value;
                    this.RaisePropertyChanged("CampaignEndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=18)]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=19)]
        public decimal VAT {
            get {
                return this.VATField;
            }
            set {
                if ((this.VATField.Equals(value) != true)) {
                    this.VATField = value;
                    this.RaisePropertyChanged("VAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=20)]
        public string EAN {
            get {
                return this.EANField;
            }
            set {
                if ((object.ReferenceEquals(this.EANField, value) != true)) {
                    this.EANField = value;
                    this.RaisePropertyChanged("EAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=21)]
        public string EAN4Sound {
            get {
                return this.EAN4SoundField;
            }
            set {
                if ((object.ReferenceEquals(this.EAN4SoundField, value) != true)) {
                    this.EAN4SoundField = value;
                    this.RaisePropertyChanged("EAN4Sound");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductUpdateResponseItem", Namespace="http://schemas.datacontract.org/2004/07/web4Sound.Contracts.Products")]
    [System.SerializableAttribute()]
    public partial class ProductUpdateResponseItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SKUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SKU {
            get {
                return this.SKUField;
            }
            set {
                if ((object.ReferenceEquals(this.SKUField, value) != true)) {
                    this.SKUField = value;
                    this.RaisePropertyChanged("SKU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string ErrorDetails {
            get {
                return this.ErrorDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDetailsField, value) != true)) {
                    this.ErrorDetailsField = value;
                    this.RaisePropertyChanged("ErrorDetails");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pim.4sound.dk/wcf/", ConfigurationName="PIMServiceEndpoint.IQueueOf_ProductQueryRequest_ProductQueryResponse")]
    public interface IQueueOf_ProductQueryRequest_ProductQueryResponse {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://pim.4sound.dk/wcf/entities/) of message ProductQueryRequest does not match the default value (http://pim.4sound.dk/wcf/)
        [System.ServiceModel.OperationContractAttribute(Action="http://pim.4sound.dk/wcf/IQueueOf_ProductQueryRequest_ProductQueryResponse/Enqueu" +
            "eMessage", ReplyAction="http://pim.4sound.dk/wcf/IQueueOf_ProductQueryRequest_ProductQueryResponse/Enqueu" +
            "eMessageResponse")]
        PimIntegration.Tasks.PIMServiceEndpoint.QueueResult EnqueueMessage(PimIntegration.Tasks.PIMServiceEndpoint.ProductQueryRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://pim.4sound.dk/wcf/entities/) of message QueueResult does not match the default value (http://pim.4sound.dk/wcf/)
        [System.ServiceModel.OperationContractAttribute(Action="http://pim.4sound.dk/wcf/IQueueOf_ProductQueryRequest_ProductQueryResponse/Dequeu" +
            "eMessage", ReplyAction="http://pim.4sound.dk/wcf/IQueueOf_ProductQueryRequest_ProductQueryResponse/Dequeu" +
            "eMessageResponse")]
        PimIntegration.Tasks.PIMServiceEndpoint.ProductQueryResponse DequeueMessage(PimIntegration.Tasks.PIMServiceEndpoint.QueueResult request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProductQueryRequest", WrapperNamespace="http://pim.4sound.dk/wcf/entities/", IsWrapped=true)]
    public partial class ProductQueryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pim.4sound.dk/wcf/", Order=0)]
        public PimIntegration.Tasks.PIMServiceEndpoint.ProductQueryRequestItem Item;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pim.4sound.dk/wcf/", Order=1)]
        public string PrimaryAction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pim.4sound.dk/wcf/", Order=2)]
        public string SecondaryAction;
        
        public ProductQueryRequest() {
        }
        
        public ProductQueryRequest(PimIntegration.Tasks.PIMServiceEndpoint.ProductQueryRequestItem Item, string PrimaryAction, string SecondaryAction) {
            this.Item = Item;
            this.PrimaryAction = PrimaryAction;
            this.SecondaryAction = SecondaryAction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueueResult", WrapperNamespace="http://pim.4sound.dk/wcf/entities/", IsWrapped=true)]
    public partial class QueueResult {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pim.4sound.dk/wcf/", Order=0)]
        public int MessageId;
        
        public QueueResult() {
        }
        
        public QueueResult(int MessageId) {
            this.MessageId = MessageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProductQueryResponse", WrapperNamespace="http://pim.4sound.dk/wcf/entities/", IsWrapped=true)]
    public partial class ProductQueryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pim.4sound.dk/wcf/", Order=0)]
        public PimIntegration.Tasks.PIMServiceEndpoint.ProductQueryResponseItem[] QueryResponseArray;
        
        public ProductQueryResponse() {
        }
        
        public ProductQueryResponse(PimIntegration.Tasks.PIMServiceEndpoint.ProductQueryResponseItem[] QueryResponseArray) {
            this.QueryResponseArray = QueryResponseArray;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQueueOf_ProductQueryRequest_ProductQueryResponseChannel : PimIntegration.Tasks.PIMServiceEndpoint.IQueueOf_ProductQueryRequest_ProductQueryResponse, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueueOf_ProductQueryRequest_ProductQueryResponseClient : System.ServiceModel.ClientBase<PimIntegration.Tasks.PIMServiceEndpoint.IQueueOf_ProductQueryRequest_ProductQueryResponse>, PimIntegration.Tasks.PIMServiceEndpoint.IQueueOf_ProductQueryRequest_ProductQueryResponse {
        
        public QueueOf_ProductQueryRequest_ProductQueryResponseClient() {
        }
        
        public QueueOf_ProductQueryRequest_ProductQueryResponseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueueOf_ProductQueryRequest_ProductQueryResponseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueueOf_ProductQueryRequest_ProductQueryResponseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueueOf_ProductQueryRequest_ProductQueryResponseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PimIntegration.Tasks.PIMServiceEndpoint.QueueResult PimIntegration.Tasks.PIMServiceEndpoint.IQueueOf_ProductQueryRequest_ProductQueryResponse.EnqueueMessage(PimIntegration.Tasks.PIMServiceEndpoint.ProductQueryRequest request) {
            return base.Channel.EnqueueMessage(request);
        }
        
        public int EnqueueMessage(PimIntegration.Tasks.PIMServiceEndpoint.ProductQueryRequestItem Item, string PrimaryAction, string SecondaryAction) {
            PimIntegration.Tasks.PIMServiceEndpoint.ProductQueryRequest inValue = new PimIntegration.Tasks.PIMServiceEndpoint.ProductQueryRequest();
            inValue.Item = Item;
            inValue.PrimaryAction = PrimaryAction;
            inValue.SecondaryAction = SecondaryAction;
            PimIntegration.Tasks.PIMServiceEndpoint.QueueResult retVal = ((PimIntegration.Tasks.PIMServiceEndpoint.IQueueOf_ProductQueryRequest_ProductQueryResponse)(this)).EnqueueMessage(inValue);
            return retVal.MessageId;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PimIntegration.Tasks.PIMServiceEndpoint.ProductQueryResponse PimIntegration.Tasks.PIMServiceEndpoint.IQueueOf_ProductQueryRequest_ProductQueryResponse.DequeueMessage(PimIntegration.Tasks.PIMServiceEndpoint.QueueResult request) {
            return base.Channel.DequeueMessage(request);
        }
        
        public PimIntegration.Tasks.PIMServiceEndpoint.ProductQueryResponseItem[] DequeueMessage(int MessageId) {
            PimIntegration.Tasks.PIMServiceEndpoint.QueueResult inValue = new PimIntegration.Tasks.PIMServiceEndpoint.QueueResult();
            inValue.MessageId = MessageId;
            PimIntegration.Tasks.PIMServiceEndpoint.ProductQueryResponse retVal = ((PimIntegration.Tasks.PIMServiceEndpoint.IQueueOf_ProductQueryRequest_ProductQueryResponse)(this)).DequeueMessage(inValue);
            return retVal.QueryResponseArray;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pim.4sound.dk/wcf/", ConfigurationName="PIMServiceEndpoint.IQueueOf_ProductUpdateRequest_ProductUpdateResponse")]
    public interface IQueueOf_ProductUpdateRequest_ProductUpdateResponse {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://pim.4sound.dk/wcf/entities/) of message ProductUpdateRequest does not match the default value (http://pim.4sound.dk/wcf/)
        [System.ServiceModel.OperationContractAttribute(Action="http://pim.4sound.dk/wcf/IQueueOf_ProductUpdateRequest_ProductUpdateResponse/Enqu" +
            "eueMessage", ReplyAction="http://pim.4sound.dk/wcf/IQueueOf_ProductUpdateRequest_ProductUpdateResponse/Enqu" +
            "eueMessageResponse")]
        PimIntegration.Tasks.PIMServiceEndpoint.QueueResult EnqueueMessage(PimIntegration.Tasks.PIMServiceEndpoint.ProductUpdateRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://pim.4sound.dk/wcf/entities/) of message QueueResult does not match the default value (http://pim.4sound.dk/wcf/)
        [System.ServiceModel.OperationContractAttribute(Action="http://pim.4sound.dk/wcf/IQueueOf_ProductUpdateRequest_ProductUpdateResponse/Dequ" +
            "eueMessage", ReplyAction="http://pim.4sound.dk/wcf/IQueueOf_ProductUpdateRequest_ProductUpdateResponse/Dequ" +
            "eueMessageResponse")]
        PimIntegration.Tasks.PIMServiceEndpoint.ProductUpdateResponse DequeueMessage(PimIntegration.Tasks.PIMServiceEndpoint.QueueResult request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProductUpdateRequest", WrapperNamespace="http://pim.4sound.dk/wcf/entities/", IsWrapped=true)]
    public partial class ProductUpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pim.4sound.dk/wcf/", Order=0)]
        public string PrimaryAction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pim.4sound.dk/wcf/", Order=1)]
        public string SecondaryAction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pim.4sound.dk/wcf/", Order=2)]
        public PimIntegration.Tasks.PIMServiceEndpoint.ProductUpdateRequestItem UpdateRequest;
        
        public ProductUpdateRequest() {
        }
        
        public ProductUpdateRequest(string PrimaryAction, string SecondaryAction, PimIntegration.Tasks.PIMServiceEndpoint.ProductUpdateRequestItem UpdateRequest) {
            this.PrimaryAction = PrimaryAction;
            this.SecondaryAction = SecondaryAction;
            this.UpdateRequest = UpdateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProductUpdateResponse", WrapperNamespace="http://pim.4sound.dk/wcf/entities/", IsWrapped=true)]
    public partial class ProductUpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pim.4sound.dk/wcf/", Order=0)]
        public PimIntegration.Tasks.PIMServiceEndpoint.ProductUpdateResponseItem[] UpdateResponseArray;
        
        public ProductUpdateResponse() {
        }
        
        public ProductUpdateResponse(PimIntegration.Tasks.PIMServiceEndpoint.ProductUpdateResponseItem[] UpdateResponseArray) {
            this.UpdateResponseArray = UpdateResponseArray;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQueueOf_ProductUpdateRequest_ProductUpdateResponseChannel : PimIntegration.Tasks.PIMServiceEndpoint.IQueueOf_ProductUpdateRequest_ProductUpdateResponse, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueueOf_ProductUpdateRequest_ProductUpdateResponseClient : System.ServiceModel.ClientBase<PimIntegration.Tasks.PIMServiceEndpoint.IQueueOf_ProductUpdateRequest_ProductUpdateResponse>, PimIntegration.Tasks.PIMServiceEndpoint.IQueueOf_ProductUpdateRequest_ProductUpdateResponse {
        
        public QueueOf_ProductUpdateRequest_ProductUpdateResponseClient() {
        }
        
        public QueueOf_ProductUpdateRequest_ProductUpdateResponseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueueOf_ProductUpdateRequest_ProductUpdateResponseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueueOf_ProductUpdateRequest_ProductUpdateResponseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueueOf_ProductUpdateRequest_ProductUpdateResponseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PimIntegration.Tasks.PIMServiceEndpoint.QueueResult PimIntegration.Tasks.PIMServiceEndpoint.IQueueOf_ProductUpdateRequest_ProductUpdateResponse.EnqueueMessage(PimIntegration.Tasks.PIMServiceEndpoint.ProductUpdateRequest request) {
            return base.Channel.EnqueueMessage(request);
        }
        
        public int EnqueueMessage(string PrimaryAction, string SecondaryAction, PimIntegration.Tasks.PIMServiceEndpoint.ProductUpdateRequestItem UpdateRequest) {
            PimIntegration.Tasks.PIMServiceEndpoint.ProductUpdateRequest inValue = new PimIntegration.Tasks.PIMServiceEndpoint.ProductUpdateRequest();
            inValue.PrimaryAction = PrimaryAction;
            inValue.SecondaryAction = SecondaryAction;
            inValue.UpdateRequest = UpdateRequest;
            PimIntegration.Tasks.PIMServiceEndpoint.QueueResult retVal = ((PimIntegration.Tasks.PIMServiceEndpoint.IQueueOf_ProductUpdateRequest_ProductUpdateResponse)(this)).EnqueueMessage(inValue);
            return retVal.MessageId;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PimIntegration.Tasks.PIMServiceEndpoint.ProductUpdateResponse PimIntegration.Tasks.PIMServiceEndpoint.IQueueOf_ProductUpdateRequest_ProductUpdateResponse.DequeueMessage(PimIntegration.Tasks.PIMServiceEndpoint.QueueResult request) {
            return base.Channel.DequeueMessage(request);
        }
        
        public PimIntegration.Tasks.PIMServiceEndpoint.ProductUpdateResponseItem[] DequeueMessage(int MessageId) {
            PimIntegration.Tasks.PIMServiceEndpoint.QueueResult inValue = new PimIntegration.Tasks.PIMServiceEndpoint.QueueResult();
            inValue.MessageId = MessageId;
            PimIntegration.Tasks.PIMServiceEndpoint.ProductUpdateResponse retVal = ((PimIntegration.Tasks.PIMServiceEndpoint.IQueueOf_ProductUpdateRequest_ProductUpdateResponse)(this)).DequeueMessage(inValue);
            return retVal.UpdateResponseArray;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pim.4sound.dk/wcf/", ConfigurationName="PIMServiceEndpoint.IQueueOf_ProductQueryRequestArray_ProductQueryResponse")]
    public interface IQueueOf_ProductQueryRequestArray_ProductQueryResponse {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://pim.4sound.dk/wcf/entities/) of message ProductQueryRequestArray does not match the default value (http://pim.4sound.dk/wcf/)
        [System.ServiceModel.OperationContractAttribute(Action="http://pim.4sound.dk/wcf/IQueueOf_ProductQueryRequestArray_ProductQueryResponse/E" +
            "nqueueMessage", ReplyAction="http://pim.4sound.dk/wcf/IQueueOf_ProductQueryRequestArray_ProductQueryResponse/E" +
            "nqueueMessageResponse")]
        PimIntegration.Tasks.PIMServiceEndpoint.QueueResult EnqueueMessage(PimIntegration.Tasks.PIMServiceEndpoint.ProductQueryRequestArray request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://pim.4sound.dk/wcf/entities/) of message QueueResult does not match the default value (http://pim.4sound.dk/wcf/)
        [System.ServiceModel.OperationContractAttribute(Action="http://pim.4sound.dk/wcf/IQueueOf_ProductQueryRequestArray_ProductQueryResponse/D" +
            "equeueMessage", ReplyAction="http://pim.4sound.dk/wcf/IQueueOf_ProductQueryRequestArray_ProductQueryResponse/D" +
            "equeueMessageResponse")]
        PimIntegration.Tasks.PIMServiceEndpoint.ProductQueryResponse DequeueMessage(PimIntegration.Tasks.PIMServiceEndpoint.QueueResult request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProductQueryRequestArray", WrapperNamespace="http://pim.4sound.dk/wcf/entities/", IsWrapped=true)]
    public partial class ProductQueryRequestArray {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pim.4sound.dk/wcf/", Order=0)]
        public string PrimaryAction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pim.4sound.dk/wcf/", Order=1)]
        public PimIntegration.Tasks.PIMServiceEndpoint.ProductQueryRequestItem[] QueryRequestArray;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pim.4sound.dk/wcf/", Order=2)]
        public string SecondaryAction;
        
        public ProductQueryRequestArray() {
        }
        
        public ProductQueryRequestArray(string PrimaryAction, PimIntegration.Tasks.PIMServiceEndpoint.ProductQueryRequestItem[] QueryRequestArray, string SecondaryAction) {
            this.PrimaryAction = PrimaryAction;
            this.QueryRequestArray = QueryRequestArray;
            this.SecondaryAction = SecondaryAction;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQueueOf_ProductQueryRequestArray_ProductQueryResponseChannel : PimIntegration.Tasks.PIMServiceEndpoint.IQueueOf_ProductQueryRequestArray_ProductQueryResponse, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueueOf_ProductQueryRequestArray_ProductQueryResponseClient : System.ServiceModel.ClientBase<PimIntegration.Tasks.PIMServiceEndpoint.IQueueOf_ProductQueryRequestArray_ProductQueryResponse>, PimIntegration.Tasks.PIMServiceEndpoint.IQueueOf_ProductQueryRequestArray_ProductQueryResponse {
        
        public QueueOf_ProductQueryRequestArray_ProductQueryResponseClient() {
        }
        
        public QueueOf_ProductQueryRequestArray_ProductQueryResponseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueueOf_ProductQueryRequestArray_ProductQueryResponseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueueOf_ProductQueryRequestArray_ProductQueryResponseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueueOf_ProductQueryRequestArray_ProductQueryResponseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PimIntegration.Tasks.PIMServiceEndpoint.QueueResult PimIntegration.Tasks.PIMServiceEndpoint.IQueueOf_ProductQueryRequestArray_ProductQueryResponse.EnqueueMessage(PimIntegration.Tasks.PIMServiceEndpoint.ProductQueryRequestArray request) {
            return base.Channel.EnqueueMessage(request);
        }
        
        public int EnqueueMessage(string PrimaryAction, PimIntegration.Tasks.PIMServiceEndpoint.ProductQueryRequestItem[] QueryRequestArray, string SecondaryAction) {
            PimIntegration.Tasks.PIMServiceEndpoint.ProductQueryRequestArray inValue = new PimIntegration.Tasks.PIMServiceEndpoint.ProductQueryRequestArray();
            inValue.PrimaryAction = PrimaryAction;
            inValue.QueryRequestArray = QueryRequestArray;
            inValue.SecondaryAction = SecondaryAction;
            PimIntegration.Tasks.PIMServiceEndpoint.QueueResult retVal = ((PimIntegration.Tasks.PIMServiceEndpoint.IQueueOf_ProductQueryRequestArray_ProductQueryResponse)(this)).EnqueueMessage(inValue);
            return retVal.MessageId;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PimIntegration.Tasks.PIMServiceEndpoint.ProductQueryResponse PimIntegration.Tasks.PIMServiceEndpoint.IQueueOf_ProductQueryRequestArray_ProductQueryResponse.DequeueMessage(PimIntegration.Tasks.PIMServiceEndpoint.QueueResult request) {
            return base.Channel.DequeueMessage(request);
        }
        
        public PimIntegration.Tasks.PIMServiceEndpoint.ProductQueryResponseItem[] DequeueMessage(int MessageId) {
            PimIntegration.Tasks.PIMServiceEndpoint.QueueResult inValue = new PimIntegration.Tasks.PIMServiceEndpoint.QueueResult();
            inValue.MessageId = MessageId;
            PimIntegration.Tasks.PIMServiceEndpoint.ProductQueryResponse retVal = ((PimIntegration.Tasks.PIMServiceEndpoint.IQueueOf_ProductQueryRequestArray_ProductQueryResponse)(this)).DequeueMessage(inValue);
            return retVal.QueryResponseArray;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pim.4sound.dk/wcf/", ConfigurationName="PIMServiceEndpoint.IQueueOf_ProductUpdateRequestArray_ProductUpdateResponse")]
    public interface IQueueOf_ProductUpdateRequestArray_ProductUpdateResponse {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://pim.4sound.dk/wcf/entities/) of message ProductUpdateRequestArray does not match the default value (http://pim.4sound.dk/wcf/)
        [System.ServiceModel.OperationContractAttribute(Action="http://pim.4sound.dk/wcf/IQueueOf_ProductUpdateRequestArray_ProductUpdateResponse" +
            "/EnqueueMessage", ReplyAction="http://pim.4sound.dk/wcf/IQueueOf_ProductUpdateRequestArray_ProductUpdateResponse" +
            "/EnqueueMessageResponse")]
        PimIntegration.Tasks.PIMServiceEndpoint.QueueResult EnqueueMessage(PimIntegration.Tasks.PIMServiceEndpoint.ProductUpdateRequestArray request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://pim.4sound.dk/wcf/entities/) of message QueueResult does not match the default value (http://pim.4sound.dk/wcf/)
        [System.ServiceModel.OperationContractAttribute(Action="http://pim.4sound.dk/wcf/IQueueOf_ProductUpdateRequestArray_ProductUpdateResponse" +
            "/DequeueMessage", ReplyAction="http://pim.4sound.dk/wcf/IQueueOf_ProductUpdateRequestArray_ProductUpdateResponse" +
            "/DequeueMessageResponse")]
        PimIntegration.Tasks.PIMServiceEndpoint.ProductUpdateResponse DequeueMessage(PimIntegration.Tasks.PIMServiceEndpoint.QueueResult request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProductUpdateRequestArray", WrapperNamespace="http://pim.4sound.dk/wcf/entities/", IsWrapped=true)]
    public partial class ProductUpdateRequestArray {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pim.4sound.dk/wcf/", Order=0)]
        public string PrimaryAction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pim.4sound.dk/wcf/", Order=1)]
        public string SecondaryAction;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pim.4sound.dk/wcf/", Order=2)]
        public PimIntegration.Tasks.PIMServiceEndpoint.ProductUpdateRequestItem[] UpdateRequestArray;
        
        public ProductUpdateRequestArray() {
        }
        
        public ProductUpdateRequestArray(string PrimaryAction, string SecondaryAction, PimIntegration.Tasks.PIMServiceEndpoint.ProductUpdateRequestItem[] UpdateRequestArray) {
            this.PrimaryAction = PrimaryAction;
            this.SecondaryAction = SecondaryAction;
            this.UpdateRequestArray = UpdateRequestArray;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQueueOf_ProductUpdateRequestArray_ProductUpdateResponseChannel : PimIntegration.Tasks.PIMServiceEndpoint.IQueueOf_ProductUpdateRequestArray_ProductUpdateResponse, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueueOf_ProductUpdateRequestArray_ProductUpdateResponseClient : System.ServiceModel.ClientBase<PimIntegration.Tasks.PIMServiceEndpoint.IQueueOf_ProductUpdateRequestArray_ProductUpdateResponse>, PimIntegration.Tasks.PIMServiceEndpoint.IQueueOf_ProductUpdateRequestArray_ProductUpdateResponse {
        
        public QueueOf_ProductUpdateRequestArray_ProductUpdateResponseClient() {
        }
        
        public QueueOf_ProductUpdateRequestArray_ProductUpdateResponseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueueOf_ProductUpdateRequestArray_ProductUpdateResponseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueueOf_ProductUpdateRequestArray_ProductUpdateResponseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueueOf_ProductUpdateRequestArray_ProductUpdateResponseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PimIntegration.Tasks.PIMServiceEndpoint.QueueResult PimIntegration.Tasks.PIMServiceEndpoint.IQueueOf_ProductUpdateRequestArray_ProductUpdateResponse.EnqueueMessage(PimIntegration.Tasks.PIMServiceEndpoint.ProductUpdateRequestArray request) {
            return base.Channel.EnqueueMessage(request);
        }
        
        public int EnqueueMessage(string PrimaryAction, string SecondaryAction, PimIntegration.Tasks.PIMServiceEndpoint.ProductUpdateRequestItem[] UpdateRequestArray) {
            PimIntegration.Tasks.PIMServiceEndpoint.ProductUpdateRequestArray inValue = new PimIntegration.Tasks.PIMServiceEndpoint.ProductUpdateRequestArray();
            inValue.PrimaryAction = PrimaryAction;
            inValue.SecondaryAction = SecondaryAction;
            inValue.UpdateRequestArray = UpdateRequestArray;
            PimIntegration.Tasks.PIMServiceEndpoint.QueueResult retVal = ((PimIntegration.Tasks.PIMServiceEndpoint.IQueueOf_ProductUpdateRequestArray_ProductUpdateResponse)(this)).EnqueueMessage(inValue);
            return retVal.MessageId;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PimIntegration.Tasks.PIMServiceEndpoint.ProductUpdateResponse PimIntegration.Tasks.PIMServiceEndpoint.IQueueOf_ProductUpdateRequestArray_ProductUpdateResponse.DequeueMessage(PimIntegration.Tasks.PIMServiceEndpoint.QueueResult request) {
            return base.Channel.DequeueMessage(request);
        }
        
        public PimIntegration.Tasks.PIMServiceEndpoint.ProductUpdateResponseItem[] DequeueMessage(int MessageId) {
            PimIntegration.Tasks.PIMServiceEndpoint.QueueResult inValue = new PimIntegration.Tasks.PIMServiceEndpoint.QueueResult();
            inValue.MessageId = MessageId;
            PimIntegration.Tasks.PIMServiceEndpoint.ProductUpdateResponse retVal = ((PimIntegration.Tasks.PIMServiceEndpoint.IQueueOf_ProductUpdateRequestArray_ProductUpdateResponse)(this)).DequeueMessage(inValue);
            return retVal.UpdateResponseArray;
        }
    }
}
